### ISSUE TITLE
error: invalid command 'bdist_egg'

### ISSUE THREAD

**Issue by vgel** [pmarti/python-messaging#30]
Caused when trying to run `python setup.py install` or `pip install -e git+<gh clone url>`. Seems to be caused by `distribute_setup.py` trying to reinstall the setuptools egg for some reason, simply commenting out the first two lines of setup.py fixed it for me.

**Comment by thijstriemstra** [comment]
I'm not sure if this project is still maintained. Would you accept a PR for a fix for this issue @pmarti?

**Comment by andrewbird** [comment]
Hi, yes we still apply things, but personally we are engaged on non related projects. Yes I'd be happy to apply this and others if people feel inclined to develop and submit patches. Python 3 support would be nice!




Sent from Samsung tablet

-------- Original message --------
From Thijs Triemstra <notifications@github.com> 
Date: 07/11/2015  18:58  (GMT+00:00) 
To pmarti/python-messaging <python-messaging@noreply.github.com> 
Subject Re: [python-messaging] error: invalid command 'bdist_egg' (#30) 
 
I'm not sure if this project is still maintained. Would you accept a PR for a fix for this issue @pmarti?

**Comment by thijstriemstra** [comment]
thanks for the reply @andrewbird. Created a PR for review.
