### ISSUE TITLE
Concatenating multi-part PDU

### ISSUE THREAD

**Issue by phi1ipp** [pmarti/python-messaging#32]
Hello,

First I want to thank you for the awesome lib! I try to get PDUs for a long message and send them to my phone to test, and I discovered that a phone doesn't concatenate them back into one SMS.

I just do `SmsSubmit('123456', 'some ... very ... long .... text').to_pdu()` and send these parts to my GSM gateway.

What could be wrong?

TIA,
Philipp

**Comment by andrewbird** [comment]
Hi Philipp,
   Do you receive two parts on the phone with the expected content halves, or nothing? If it's two parts, then perhaps the receiving phone doesn't support extended SMS. If it's nothing, then perhaps you didn't get all the parts. Just be sure to send all the parts from one invocation of to_pdu(). I seem to remember that each message contains a sequence number, total message count, and a random id number for the set. For proper reassembly, you need all the parts, it doesn't matter what order they are in, the originating number must be the same on all and the id must also be the same.
You also need to see that your gateway is sending the PDU raw, not treating it as text and wrapping it up in another PDU that it generates. If you can intercept the output PDUs it produces somehow, then view them with a tool like PDUspy (runs under wine), you can check all the things I mentioned above.
Hope it helps

**Comment by phi1ipp** [comment]
Hi Andrew,

Thank you for coming back with the help. I was able to figure out that 
it's my phone's issues. Other people receive the SMS as one big message, 
so all is fine!

**Comment by andrewbird** [comment]
I'm to have been some help. Good luck with your project.
