### ISSUE TITLE
How get a MMS message?

### ISSUE THREAD

**Issue by toniss** [pmarti/python-messaging#35]
Hi, the content of the tutorials folder isnt enough to successfully retrieve  a mms message from the mmsc, I will glad if you describe how do it.

**Comment by andrewbird** [comment]
Hi there, 
 Python-messaging doesn't deal with transmission or reception of messages itself, but merely provides the means to encode or decode the messages. That said the method is something like this:
1 a message is received at the provider's MMSC
2 the MMSC sends enhanced SMS containing WAP push to user
3 user decodes WAP push, sees that it contains a URL describing the location of the MMS on the provider's datastore.
4 the user creates PDP context to providers WAP APN
5 user connects to WAP gateway, and does http get to retrieve MMS body
6 user decodes MMS into constituant parts.

Note this description is only for providers whom offer WAP 2.0 service.  For WAP 1.1, you'll need a WSP stack as it doesn't use TCP. I never tried that though.

**Comment by andrewbird** [comment]
I also seem to remember that Wader automated some of the notification, decoding the WAP push and sending a dbus signal, but the actual reception had to be done by the client,  which I think was v-mobile-broadband. But I never worked on the MMS part of the project, so I'm not too sure.

**Comment by andrewbird** [comment]
Timeout!
